@baseUrl = http://localhost:8080/api

##############
# RESEARCHER #
##############

### Create
POST {{baseUrl}}/researchers
Content-Type: application/json

{
    "name": "a",
    "email": "a@A"
}

### Delete
@deleteUUID =  
DELETE {{baseUrl}}/researchers/{{deleteUUID}}

### Find by Id
@findUUID = 
GET {{baseUrl}}/researchers/{{findUUID}}

### Search by name
@searchName = 
GET {{baseUrl}}/researchers/search?name={{searchName}}

### Check email availability
@checkEmail = 
GET {{baseUrl}}/researchers/email-availability?email={{checkEmail}}

#############
# WORKFLOWS #
#############

### Create
POST {{baseUrl}}/workflows
Content-Type: application/json

{
  "statuses": [
    { "name": "Draft" },
    { "name": "Completed"}
  ]
}

### Find All
GET {{baseUrl}}/workflows

### Find by Id
@findUUID = 
GET {{baseUrl}}/workflows/{{findUUID}}

#####################
# EXPERIMENT STATUS #
#####################

### Find By Workflow and Order By Sequence Order
@findUUID = 
GET  {{baseUrl}}/experiment-statuses?workflowId={{findUUID}}