@baseUrl = http://localhost:8080/api

### Create
POST {{baseUrl}}/researchers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com"
}

### Delete
@deleteUUID = 5313d9d3-1160-4251-a29f-167990384bce
DELETE {{baseUrl}}/researchers/{{deleteUUID}}

### Find by Id
@findUUID = 37f7d38d-d9ec-4697-8729-2e7ee764bf57
GET {{baseUrl}}/researchers/{{findUUID}}

### Search by name
@searchName = John
GET {{baseUrl}}/researchers/search?name={{searchName}}

### Check email availability
@checkEmail = researcher@example.com
GET {{baseUrl}}/researchers/email-availability?email={{checkEmail}}

### Toggle activation
@toogleActivationUUID = c572f056-5bb9-4a74-bac5-0c9dedaba33c
PATCH {{baseUrl}}/researchers/{{toogleActivationUUID}}/toggle-active

### Update
@updateUUID = b29a7c3b-5d85-46e0-9157-a224d20cb5d6
PUT {{baseUrl}}/researchers/{{updateUUID}}
Content-Type: application/json

{
    "name": "",
    "email": "edited@example.com"
}
